# Example for production SSD storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-ssd
  annotations:
    description: "Fast SSD storage for production workloads"
# Uncomment and configure for your cloud provider:
# AWS EKS:
# provisioner: kubernetes.io/aws-ebs
# parameters:
#   type: gp3
#   fsType: ext4

# GKE:
# provisioner: kubernetes.io/gce-pd
# parameters:
#   type: pd-ssd

# Azure:
# provisioner: kubernetes.io/azure-disk
# parameters:
#   storageaccounttype: Premium_LRS
#   kind: Managed

provisioner: kubernetes.io/no-provisioner  # Replace with your provider
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
