global:
  imageRegistry: "localhost:5000"
  imageTag: "latest"
  imagePullPolicy: IfNotPresent

env:
  enabled: true
  service:
    type: NodePort
    port: 5000
    targetPort: 5000
    nodePort: 8000
  
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

  storage:
    enabled: true
    accessMode: "ReadWriteOnce"
    storageClass: "local-path"
    size: "5Gi"

training:
  enabled: true
  service:
    type: ClusterIP
    port: 50051
    targetPort: 50051
  args:
    port: "50051"

  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "400m"
  storage:
    enabled: true
    accessMode: "ReadWriteOnce"
    storageClass: "local-path"
    size: "5Gi"

inference:
  enabled: true
  args:
    envHost: "env:5000"
    grpcHost: "training"
    grpcPort: "50051"
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "400m"

  storage:
    enabled: true
    accessMode: "ReadWriteOnce"
    storageClass: "local-path"
    size: "5Gi"

# SyncService Configuration for Local Development
sync:
  enabled: true
  args:
    frequency: 5.0  # Lower frequency for local development
    verbose: true   # Enable verbose logging for debugging
  resources:
    requests:
      memory: "32Mi"
      cpu: "25m"
    limits:
      memory: "64Mi"
      cpu: "50m"

rabbitmq:
  enabled: false

logging:
  level: "DEBUG"
  enableConsoleLogs: true