{{- if .Values.storage.logs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "snake-rl.fullname" . }}-logs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snake-rl.labels" . | nindent 4 }}
    component: logs-storage
spec:
  accessModes:
    - {{ .Values.storage.logs.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.logs.size }}
  {{- if .Values.storage.logs.storageClass }}
  storageClassName: {{ .Values.storage.logs.storageClass }}
  {{- end }}
{{- end }}