# ClickHouse Helm Values

global:
  storageClass: "local-path"

auth:
  # Use Kubernetes secret for password
  existingSecret: "clickhouse-credentials"
  existingSecretKey: "password"
  
persistence:
  enabled: true
  storageClass: "local-path"
  size: 100Gi
  accessModes:
    - ReadWriteOnce
  mountPath: /data-storage/hdd2/persistence_volumes/clickhouse

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi

commonLabels: {}
commonAnnotations: {}

service:
  type: NodePort
  ports:
    http: 8123
    tcp: 9000
  nodePorts:
    http: 8123
    tcp: 9000

metrics:
  enabled: true
  serviceMonitor:
    enabled: false

zookeeper:
  enabled: true
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "local-path"
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

shards: 1
replicaCount: 1

configuration: |
  <clickhouse>
    <logger>
      <level>information</level>
    </logger>
    <http_port>8123</http_port>
    <tcp_port>9000</tcp_port>
    <interserver_http_port>9009</interserver_http_port>
    <listen_host>::</listen_host>
    <max_connections>4096</max_connections>
    <keep_alive_timeout>3</keep_alive_timeout>
    <max_concurrent_queries>100</max_concurrent_queries>
    <uncompressed_cache_size>8589934592</uncompressed_cache_size>
    <mark_cache_size>5368709120</mark_cache_size>
  </clickhouse>

users: |
  <clickhouse>
    <users>
      <default>
        <networks>
          <ip>::/0</ip>
        </networks>
        <profile>default</profile>
        <quota>default</quota>
      </default>
    </users>
    <profiles>
      <default>
        <max_memory_usage>10000000000</max_memory_usage>
        <use_uncompressed_cache>0</use_uncompressed_cache>
        <load_balancing>random</load_balancing>
      </default>
    </profiles>
    <quotas>
      <default>
        <interval>
          <duration>3600</duration>
          <queries>0</queries>
          <errors>0</errors>
          <result_rows>0</result_rows>
          <read_rows>0</read_rows>
          <execution_time>0</execution_time>
        </interval>
      </default>
    </quotas>
  </clickhouse>
