env:
  enabled: true
  args:
    gridWidth: 11
    gridHeight: 11
    fps: 100
    seed: 16
    maxStepsWithoutFood: 505
    visionRadius: 5
    rewardConfig: '{"alive": 0.1, "eat_food": 1.0, "game_over": -1.0}'

inference:
  enabled: true
  runAsJob: true
  args:
    snakeId: "adam"
    envHost: "go-16-00244-env:5000"
    maxEpisodes: 1000
    learningRate: 0.001
    beta: 0.0001
    batchSize: 32
    gamma: 0.95

experiment:
  name: "game_over_maxsteps505_beta0_0001_lr0_001"
