apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    purpose: observability
    environment: shared
  annotations:
    description: "Monitoring stack (Prometheus, Grafana)"
