createNamespace: false
global:
  imageRegistry: "localhost:5000"
  imageTag: "latest"
  imagePullPolicy: Always

# ==== ENVIRONMENT SERVER CONFIGURATION ====
env:
  enabled: true       # Set to true to run the always-on Environment service
  image:
    repository: "snake-rl/env"
    tag: ""
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
  args:
    fps: 100
    seed: 1
    maxStepsWithoutFood: 50
    gridWidth: 11
    gridHeight: 11
    visionRadius: 5
    visionDisplayCols: 11
    visionDisplayRows: 11
    maxSnakes: 1
    rewardConfig: '{"alive":0, "eat_food":1, "game_over":-1}'
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  replicaCount: 1
  storage:
    enabled: true
    accessMode: "ReadWriteOnce"
    storageClass: "local-path"
    size: "5Gi"

# ==== INFERENCE/AGENT EXPERIMENT JOB CONFIGURATION ====
inference:
  enabled: true      # Set to true for inference, false if only running env
  runAsJob: true      # Switch between Job and StatefulSet/Deployment
  image:
    repository: "snake-rl/inference"
    tag: ""
  args:
    snakeId: "adam"
    envHost: "snake-rl-env:5000" # Use env service DNS name (host:port)
    modelSaveDir: "/output/models"
    logFile: "/output/agent1.log"
    batchSize: 1
    maxEpisodes: 1000
    learningRate: 0.001
    gamma: 0.95
    beta: 0.1
  resources:
    requests:
      memory: "1Gi"
      cpu: "2000m"
    limits:
      memory: "1Gi"
      cpu: "2000m"
  ttlSecondsAfterFinished: 1200
  storage:
    enabled: true
    accessMode: "ReadWriteOnce"
    storageClass: "local-path"
    size: "5Gi"

envContainer:
  command: []
  args: []

inferenceContainer:
  command: []
  args: []

run:
  maxEpisodes: 1000
  ttlSecondsAfterFinished: 10

# ==== STORAGE SHARED AMONG COMPONENTS ====
storage:
  enabled: true
  accessMode: "ReadWriteOnce"
  storageClass: "local-path"
  size: "10Gi"

# ==== RABBITMQ CONFIGURATION ====
rabbitmq:
  enabled: true
  host: "rabbitmq.data-stack.svc.cluster.local"
  port: 5672
  username: "tech"
  password: "tech"
  vhost: "/"
  exchange: ""
  routingKey: "rabbitmq_rl_snake_logs"
  exchangeType: "direct"
  durable: true
  async: false
  connectionTimeout: 10
  retryDelay: 5
  maxRetries: 3

# ==== LOGGING ====
logging:
  level: "DEBUG"
  enableConsoleLogs: true
  file: ""

# ==== EXPERIMENT TAGGING ====
experiment:
  name: "test_reward"
# ==== NETWORK POLICY ====
networkPolicy:
  enabled: false

