createNamespace: false
global:
  imageRegistry: "localhost:5000"
  imageTag: "latest"
  imagePullPolicy: Always


# Environment Service Configuration
env:
  enabled: false   # for Job, disable separate deployment
  image:
    repository: "snake-rl/env"
    tag: ""

  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000

  args:
    fps: 100
    seed: 1
    maxStepsWithoutFood: 1000
    gridWidth: 11
    gridHeight: 11
    visionRadius: 5
    visionDisplayCols: 11
    visionDisplayRows: 11
    maxSnakes: 1
    rewardConfig: '{"alive": 0.1, "eat_food":0.5, "game_over":0 }'

  resources:
    requests:
      memory: "256Mi"
      cpu: "1000m"
    limits:
      memory: "512Mi"
      cpu: "2000m"

  storage:
    enabled: true
    accessMode: "ReadWriteOnce"
    storageClass: "local-path"
    size: "5Gi"

envContainer:
  command: []
  args: []

# Inference Service Configuration
inference:
  enabled: false  # for Job, disable separate deployment
  image:
    repository: "snake-rl/inference"
    tag: ""

  args:
    snakeId: "adam"
    modelSaveDir: "/output/models"
    logFile: "/output/agent1.log"
    batchSize: 1
    learningRate: 0.001
    gamma: 0.9
    beta: 0.05


  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "400m"

  storage:
    enabled: true
    accessMode: "ReadWriteOnce"
    storageClass: "local-path"
    size: "5Gi"

inferenceContainer:
  command: []
  args: []

run:
  maxEpisodes: 10
  ttlSecondsAfterFinished: 10

storage:
  enabled: true
  accessMode: "ReadWriteOnce"
  storageClass: "local-path"
  size: "10Gi"

# RabbitMQ Configuration
rabbitmq:
  enabled: true
  host: "rabbitmq.data-stack.svc.cluster.local"
  port: 5672
  username: "tech"
  password: "tech"
  vhost: "/"
  exchange: ""
  routingKey: "rabbitmq_rl_snake_logs"
  exchangeType: "direct"
  durable: true
  async: false
  connectionTimeout: 10
  retryDelay: 5
  maxRetries: 3

# Logging Configuration
logging:
  level: "DEBUG"
  enableConsoleLogs: true

# Experiment Configuration
experiment:
  name: "test_job"

# Network Configuration
networkPolicy:
  enabled: false



